baseurl = "/"
languageCode = "en-us"
title = "~"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:slug/"

[[menu.main]]
    name = "Cats"
    url = "/categories/"
    weight = 1
[[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 2
#[[menu.main]]
#    name = "Skills"
#    url = "/skills/"
#    weight = 3
[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 4
#[[menu.feed]]
#    name = "Subscribe"
#    url = "/index.xml"

[params]
    description = "life is too short to be an asshole."
    footer = "hrishikeshbman [at] gmail [dot] com | [Github](https://github.com/geekodour) | [Twitter](https://twitter.com/geekodour)"
    custom_css = ["css/theme-override.css"]
